services:
  netcup-dyndns:
    image: netcup-dyndns
    build:
      context: ..
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    env_file:
      - ../.env
    ports:
      - 9229:9229
    command: ['node', '--inspect=0.0.0.0:9229', './dist/index.js']
